services:
  backend:
    container_name: tiendauni-api
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tienda_uni
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      ERROR_URL: ${ERROR_URL}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: tiendauni-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tienda_uni
    ports:
      - "5435:5432"
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d tienda_uni" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: