spring:
  application:
    name: TiendaUniApi
  datasource:
    username: root
    password: 1234
    url: jdbc:postgresql://localhost:5432/tienda_uni
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
server:
  servlet:
    context-path: /api

jwt:
  secret: mysecretkey
  expiration:
    access-token: 900 # 15 minutes in seconds
    refresh-token: 604800 # 7 days in seconds
  issuer: tiendauni

app:
  cookie:
    secure: false
  url:
    error: https://example.com/errors