spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
  jpa:
    show-sql: false # Apagado para no saturar los logs de producción y mejorar el rendimiento
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

jwt:
  secret: ${JWT_SECRET} # Clave inyectada de forma segura mediante variables de entorno

app:
  cookie:
    secure: true # Activado para forzar que las cookies solo viajen sobre HTTPS
  cors:
    allowed-origins: ${FRONTEND_URL} # Variable de entorno inyectada por Docker
  url:
    error: ${ERROR_URL} # Frontend prod al que se redirige en errores de auth
  mail:
    sender:
      email: ${EMAIL_SENDER} # Dirección de correo del remitente inyectada por Docker
