spring:
  application:
    name: TiendaUniApi
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api

jwt:
  expiration:
    access-token: 900 # 15 minutes in seconds
    refresh-token: 604800 # 7 days in seconds
  issuer: tiendauni