INSERT INTO tags (name, type)
VALUES ('FOOD', 'CATEGORY'),
       ('DRINKS', 'CATEGORY'),
       ('ELECTRONICS', 'CATEGORY'),
       ('CLOTHING', 'CATEGORY'),
       ('FURNITURE', 'CATEGORY'),
       ('BOOKS', 'CATEGORY'),
       ('TOYS', 'CATEGORY'),
       ('BEAUTY', 'CATEGORY'),
       ('SPORTS', 'CATEGORY'),
       ('AUTOMOTIVE', 'CATEGORY'),
       ('PETS', 'CATEGORY'),
       ('MUSIC', 'CATEGORY'),
       ('ART', 'CATEGORY'),
       ('JEWELRY', 'CATEGORY'),
       ('GARDENING', 'CATEGORY'),
       ('HEALTH', 'CATEGORY'),
       ('TRAVEL', 'CATEGORY'),
       ('HOBBIES', 'CATEGORY'),
       ('CASH', 'PAYMENT_METHOD'),
       ('BANK_TRANSFER', 'PAYMENT_METHOD'),
       ('PAYPAL', 'PAYMENT_METHOD'),
       ('CRYPTOCURRENCY', 'PAYMENT_METHOD'),
       ('DEBIT_CARD', 'PAYMENT_METHOD'),
       ('NO_SALES', 'SALE_MODIFIER');